/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { NotebookAddSourceRequest, NotebookArtifactRequest, NotebookDeleteRequest, NotebookDeleteResult, NotebookEntry, NotebookGetRequest, NotebookListRequest, NotebookListResult, NotebookPutRequest, NotebookRemoveSourceRequest, NotebookRemoveSourceResult, NotebookSourceSelectionRequest, NotebookSummaryRequest } from '@deepseek-ai/dsh-notebooks/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6e6f7465626f6f6b73 {
    addSource: (request: NotebookAddSourceRequest) => Promise<RemoteResult<NotebookEntry>>
    delete: (request: NotebookDeleteRequest) => Promise<RemoteResult<NotebookDeleteResult>>
    get: (request: NotebookGetRequest) => Promise<RemoteResult<NotebookEntry | null>>
    list: (request: NotebookListRequest) => Promise<RemoteResult<NotebookListResult>>
    put: (request: NotebookPutRequest) => Promise<RemoteResult<NotebookEntry>>
    removeSource: (request: NotebookRemoveSourceRequest) => Promise<RemoteResult<NotebookRemoveSourceResult>>
    setArtifact: (request: NotebookArtifactRequest) => Promise<RemoteResult<NotebookEntry>>
    setSourceSelection: (request: NotebookSourceSelectionRequest) => Promise<RemoteResult<NotebookEntry>>
    setSummary: (request: NotebookSummaryRequest) => Promise<RemoteResult<NotebookEntry>>
  }
  interface TypertRemoteMap {
    'notebooks/addSource': (request: NotebookAddSourceRequest) => Promise<RemoteResult<NotebookEntry>>
    'notebooks/delete': (request: NotebookDeleteRequest) => Promise<RemoteResult<NotebookDeleteResult>>
    'notebooks/get': (request: NotebookGetRequest) => Promise<RemoteResult<NotebookEntry | null>>
    'notebooks/list': (request: NotebookListRequest) => Promise<RemoteResult<NotebookListResult>>
    'notebooks/put': (request: NotebookPutRequest) => Promise<RemoteResult<NotebookEntry>>
    'notebooks/removeSource': (request: NotebookRemoveSourceRequest) => Promise<RemoteResult<NotebookRemoveSourceResult>>
    'notebooks/setArtifact': (request: NotebookArtifactRequest) => Promise<RemoteResult<NotebookEntry>>
    'notebooks/setSourceSelection': (request: NotebookSourceSelectionRequest) => Promise<RemoteResult<NotebookEntry>>
    'notebooks/setSummary': (request: NotebookSummaryRequest) => Promise<RemoteResult<NotebookEntry>>
  }
  interface TypertRemoteNamespaceMap {
    'notebooks': TypertRemoteNamespace$6e6f7465626f6f6b73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
