/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_notebooks_notebooks_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_delete_result$schema = z.object({
  'deleted': z.boolean().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_list_parameter_0$schema = z.object({
  'query': z.string().readonly().optional(),
  'tag': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_notebooks_notebooks_list_result$schema = z.object({
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_put_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly().optional(),
})
const _deepseek_ai_dsh_notebooks_notebooks_put_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-notebooks',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/delete',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookDeleteRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookDeleteResult',
        schema: _deepseek_ai_dsh_notebooks_notebooks_delete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":127,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/list',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookListRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookListResult',
        schema: _deepseek_ai_dsh_notebooks_notebooks_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":83,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/put',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'put',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookPutRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_put_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookEntry',
        schema: _deepseek_ai_dsh_notebooks_notebooks_put_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":98,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable notebook service.",
        "summary": "Durable notebook service.",
        "tags": [],
        "jsDoc": "/** Durable notebook service. */",
        "key": "notebooks",
        "exportName": "NotebooksService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: NotebookListRequest): NotebookListResult",
            "summary": "List entries matching optional text and tag filters.",
            "jsDoc": "/** List entries matching optional text and tag filters. */"
          },
          {
            "kind": "method",
            "name": "put",
            "signature": "@Remote('put') put(request: NotebookPutRequest): Promise<NotebookEntry>",
            "summary": "Create or replace an entry after validating configured limits.",
            "jsDoc": "/** Create or replace an entry after validating configured limits. */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: NotebookDeleteRequest): Promise<NotebookDeleteResult>",
            "summary": "Delete an entry; absence is a successful stable outcome.",
            "jsDoc": "/** Delete an entry; absence is a successful stable outcome. */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "NotebookDeleteRequest",
            "declaration": "export interface NotebookDeleteRequest {\n    readonly id: NotebookId;\n}"
          },
          {
            "name": "NotebookDeleteResult",
            "declaration": "export interface NotebookDeleteResult {\n    readonly deleted: boolean;\n}"
          },
          {
            "name": "NotebookEntry",
            "declaration": "export interface NotebookEntry {\n    readonly id: NotebookId;\n    readonly title: string;\n    readonly content: string;\n    readonly tags: string[];\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "NotebookId",
            "declaration": "export type NotebookId = Branded<'NotebookId'>;"
          },
          {
            "name": "NotebookListRequest",
            "declaration": "export interface NotebookListRequest {\n    readonly query?: string;\n    readonly tag?: string;\n}"
          },
          {
            "name": "NotebookListResult",
            "declaration": "export interface NotebookListResult {\n    readonly entries: NotebookEntry[];\n}"
          },
          {
            "name": "NotebookPutRequest",
            "declaration": "export interface NotebookPutRequest {\n    readonly id?: NotebookId;\n    readonly title: string;\n    readonly content: string;\n    readonly tags?: string[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
