/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  TypeRTRemoteContribution,
} from '@deepseek-ai/dsh-type-meta'
import type { NotebookDeleteRequest, NotebookDeleteResult, NotebookEntry, NotebookListRequest, NotebookListResult, NotebookPutRequest } from '@deepseek-ai/dsh-notebooks/types'

declare module '@deepseek-ai/dsh-type-meta' {
  interface TypeRTRemoteNamespace$6e6f7465626f6f6b73 {
    delete: (request: NotebookDeleteRequest) => Promise<NotebookDeleteResult>
    list: (request: NotebookListRequest) => Promise<NotebookListResult>
    put: (request: NotebookPutRequest) => Promise<NotebookEntry>
  }
  interface TypeRTRemoteMap {
    'notebooks/delete': (request: NotebookDeleteRequest) => Promise<NotebookDeleteResult>
    'notebooks/list': (request: NotebookListRequest) => Promise<NotebookListResult>
    'notebooks/put': (request: NotebookPutRequest) => Promise<NotebookEntry>
  }
  interface TypeRTRemoteNamespaceMap {
    'notebooks': TypeRTRemoteNamespace$6e6f7465626f6f6b73
  }
}

export declare const TYPERT_REMOTE: TypeRTRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
