/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_notebooks_notebooks_addSource_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.string().readonly().optional(),
  'mimeType': z.string().readonly().optional(),
  'content': z.string().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_addSource_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_delete_result$schema = z.object({
  'deleted': z.boolean().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_get_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_get_result$schema = z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})])
const _deepseek_ai_dsh_notebooks_notebooks_list_parameter_0$schema = z.object({
  'query': z.string().readonly().optional(),
  'tag': z.string().readonly().optional(),
  'sourceKind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly().optional(),
})
const _deepseek_ai_dsh_notebooks_notebooks_list_result$schema = z.object({
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_put_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly().optional(),
  'tags': z.array(z.string()).readonly().optional(),
})
const _deepseek_ai_dsh_notebooks_notebooks_put_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_removeSource_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'sourceId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_removeSource_result$schema = z.object({
  'removed': z.boolean().readonly(),
  'entry': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_setArtifact_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_setArtifact_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_setSourceSelection_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'sourceIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_setSourceSelection_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_setSummary_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'summary': z.string().readonly(),
})
const _deepseek_ai_dsh_notebooks_notebooks_setSummary_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'summary': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'sources': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("manual"), z.literal("url"), z.literal("document"), z.literal("chat_answer")]).readonly(),
  'name': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'mimeType': z.union([z.literal(null), z.string()]).readonly(),
  'content': z.string().readonly(),
  'selected': z.boolean().readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("mindmap"), z.literal("report")]).readonly(),
  'content': z.string().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-notebooks',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/addSource',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'addSource',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookAddSourceRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_addSource_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookEntry',
        schema: _deepseek_ai_dsh_notebooks_notebooks_addSource_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":169,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/delete',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookDeleteRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookDeleteResult',
        schema: _deepseek_ai_dsh_notebooks_notebooks_delete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":244,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/get',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookGetRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks#notebooks/get:result',
        schema: _deepseek_ai_dsh_notebooks_notebooks_get_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":128,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/list',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookListRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookListResult',
        schema: _deepseek_ai_dsh_notebooks_notebooks_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":110,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/put',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'put',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookPutRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_put_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookEntry',
        schema: _deepseek_ai_dsh_notebooks_notebooks_put_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":139,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/removeSource',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'removeSource',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookRemoveSourceRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_removeSource_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookRemoveSourceResult',
        schema: _deepseek_ai_dsh_notebooks_notebooks_removeSource_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":204,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/setArtifact',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'setArtifact',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookArtifactRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_setArtifact_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookEntry',
        schema: _deepseek_ai_dsh_notebooks_notebooks_setArtifact_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":229,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/setSourceSelection',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'setSourceSelection',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookSourceSelectionRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_setSourceSelection_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookEntry',
        schema: _deepseek_ai_dsh_notebooks_notebooks_setSourceSelection_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":189,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-notebooks#notebooks/setSummary',
      service: 'notebooks',
      namespace: 'notebooks',
      method: 'setSummary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookSummaryRequest',
            schema: _deepseek_ai_dsh_notebooks_notebooks_setSummary_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-notebooks/types#NotebookEntry',
        schema: _deepseek_ai_dsh_notebooks_notebooks_setSummary_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/notebooks/src/index.ts","line":219,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable notebook service.",
        "summary": "Durable notebook service.",
        "tags": [],
        "jsDoc": "/** Durable notebook service. */",
        "key": "notebooks",
        "exportName": "NotebooksService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: NotebookListRequest): NotebookListResult",
            "summary": "List entries matching optional text, tag, and source filters.",
            "jsDoc": "/**\n * List entries matching optional text, tag, and source filters.\n * @param request - optional notebook filters.\n * @returns matching entries ordered by newest edit.\n */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(request: NotebookGetRequest): NotebookEntry | null",
            "summary": "Read one exact notebook.",
            "jsDoc": "/**\n * Read one exact notebook.\n * @param request - notebook identity to read.\n * @returns detached notebook data, or null when absent.\n */"
          },
          {
            "kind": "method",
            "name": "put",
            "signature": "@Remote('put') put(request: NotebookPutRequest): Promise<NotebookEntry>",
            "summary": "Create or replace a notebook after validating configured limits.",
            "jsDoc": "/**\n * Create or replace a notebook after validating configured limits.\n * @param request - complete notebook write request.\n * @returns the detached stored notebook.\n */"
          },
          {
            "kind": "method",
            "name": "addSource",
            "signature": "@Remote('addSource') addSource(request: NotebookAddSourceRequest): Promise<NotebookEntry>",
            "summary": "Attach a selected source to a notebook.",
            "jsDoc": "/**\n * Attach a selected source to a notebook.\n * @param request - source content and owning notebook identity.\n * @returns the updated detached notebook.\n */"
          },
          {
            "kind": "method",
            "name": "setSourceSelection",
            "signature": "@Remote('setSourceSelection') setSourceSelection(request: NotebookSourceSelectionRequest): Promise<NotebookEntry>",
            "summary": "Replace the source selection used for summaries and Studio artifacts.",
            "jsDoc": "/**\n * Replace the source selection used for summaries and Studio artifacts.\n * @param request - owning notebook and selected source identities.\n * @returns the updated detached notebook.\n */"
          },
          {
            "kind": "method",
            "name": "removeSource",
            "signature": "@Remote('removeSource') removeSource(request: NotebookRemoveSourceRequest): Promise<NotebookRemoveSourceResult>",
            "summary": "Remove one source and report whether it existed.",
            "jsDoc": "/**\n * Remove one source and report whether it existed.\n * @param request - notebook and source identities.\n * @returns the removal outcome and updated notebook.\n */"
          },
          {
            "kind": "method",
            "name": "setSummary",
            "signature": "@Remote('setSummary') setSummary(request: NotebookSummaryRequest): Promise<NotebookEntry>",
            "summary": "Replace the overview synthesized from selected sources.",
            "jsDoc": "/**\n * Replace the overview synthesized from selected sources.\n * @param request - notebook identity and new overview.\n * @returns the updated detached notebook.\n */"
          },
          {
            "kind": "method",
            "name": "setArtifact",
            "signature": "@Remote('setArtifact') setArtifact(request: NotebookArtifactRequest): Promise<NotebookEntry>",
            "summary": "Create or replace a report or Mermaid mind-map artifact.",
            "jsDoc": "/**\n * Create or replace a report or Mermaid mind-map artifact.\n * @param request - notebook identity and Studio artifact content.\n * @returns the updated detached notebook.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: NotebookDeleteRequest): Promise<NotebookDeleteResult>",
            "summary": "Delete an entry; absence is a successful stable outcome.",
            "jsDoc": "/**\n * Delete an entry; absence is a successful stable outcome.\n * @param request - notebook identity to delete.\n * @returns whether the notebook existed.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "NotebookAddSourceRequest",
            "declaration": "export interface NotebookAddSourceRequest {\n    readonly id: NotebookId;\n    readonly kind: NotebookSourceKind;\n    readonly name: string;\n    readonly url?: string;\n    readonly mimeType?: string;\n    readonly content: string;\n}"
          },
          {
            "name": "NotebookArtifact",
            "declaration": "export interface NotebookArtifact {\n    readonly kind: NotebookArtifactKind;\n    readonly content: string;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "NotebookArtifactKind",
            "declaration": "export type NotebookArtifactKind = 'mindmap' | 'report';"
          },
          {
            "name": "NotebookArtifactRequest",
            "declaration": "export interface NotebookArtifactRequest {\n    readonly id: NotebookId;\n    readonly kind: NotebookArtifactKind;\n    readonly content: string;\n}"
          },
          {
            "name": "NotebookDeleteRequest",
            "declaration": "export interface NotebookDeleteRequest {\n    readonly id: NotebookId;\n}"
          },
          {
            "name": "NotebookDeleteResult",
            "declaration": "export interface NotebookDeleteResult {\n    readonly deleted: boolean;\n}"
          },
          {
            "name": "NotebookEntry",
            "declaration": "export interface NotebookEntry {\n    readonly id: NotebookId;\n    readonly title: string;\n    readonly content: string;\n    readonly summary: string;\n    readonly tags: string[];\n    readonly sources: NotebookSource[];\n    readonly artifacts: NotebookArtifact[];\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "NotebookGetRequest",
            "declaration": "export interface NotebookGetRequest {\n    readonly id: NotebookId;\n}"
          },
          {
            "name": "NotebookId",
            "declaration": "export type NotebookId = Branded<'NotebookId'>;"
          },
          {
            "name": "NotebookListRequest",
            "declaration": "export interface NotebookListRequest {\n    readonly query?: string;\n    readonly tag?: string;\n    readonly sourceKind?: NotebookSourceKind;\n}"
          },
          {
            "name": "NotebookListResult",
            "declaration": "export interface NotebookListResult {\n    readonly entries: NotebookEntry[];\n}"
          },
          {
            "name": "NotebookPutRequest",
            "declaration": "export interface NotebookPutRequest {\n    readonly id?: NotebookId;\n    readonly title: string;\n    readonly content: string;\n    readonly summary?: string;\n    readonly tags?: string[];\n}"
          },
          {
            "name": "NotebookRemoveSourceRequest",
            "declaration": "export interface NotebookRemoveSourceRequest {\n    readonly id: NotebookId;\n    readonly sourceId: NotebookSourceId;\n}"
          },
          {
            "name": "NotebookRemoveSourceResult",
            "declaration": "export interface NotebookRemoveSourceResult {\n    readonly removed: boolean;\n    readonly entry: NotebookEntry;\n}"
          },
          {
            "name": "NotebookSource",
            "declaration": "export interface NotebookSource {\n    readonly id: NotebookSourceId;\n    readonly kind: NotebookSourceKind;\n    readonly name: string;\n    readonly url: string | null;\n    readonly mimeType: string | null;\n    readonly content: string;\n    readonly selected: boolean;\n    readonly createdAt: number;\n}"
          },
          {
            "name": "NotebookSourceId",
            "declaration": "export type NotebookSourceId = Branded<'NotebookSourceId'>;"
          },
          {
            "name": "NotebookSourceKind",
            "declaration": "export type NotebookSourceKind = 'manual' | 'url' | 'document' | 'chat_answer';"
          },
          {
            "name": "NotebookSourceSelectionRequest",
            "declaration": "export interface NotebookSourceSelectionRequest {\n    readonly id: NotebookId;\n    readonly sourceIds: NotebookSourceId[];\n}"
          },
          {
            "name": "NotebookSummaryRequest",
            "declaration": "export interface NotebookSummaryRequest {\n    readonly id: NotebookId;\n    readonly summary: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
